services:
  postfix:
    build:
      context: .
      args:
        APP_USER: ${APP_USER}
        APP_PASSWORD: ${APP_PASSWORD}
        MAIL_NAME: ${MAIL_NAME}
        SMTP_DOMAIN: ${SMTP_DOMAIN}
        SMTP_PORT: ${SMTP_PORT}
    container_name: postfix
    ports:
      - ${HOST_PORT}:25
    restart: unless-stopped
networks:
  default:
    name: shared 
    external: true
