services:
  smtp:
    build:
      context: .
      args:
        EMAIL_USER: ${APP_USER}
        EMAIL_PASSWORD: ${APP_PASSWORD}
        ALIAS_EMAIL: ${ALIAS_EMAIL}
        MAIL_NAME: ${MAIL_NAME}
        SMTP_DOMAIN: ${SMTP_DOMAIN}
        SMTP_PORT: ${SMTP_PORT}
    container_name: postfix
    ports:
      - ${PORT}:25
    restart: unless-stopped
#networks:
#  default:
#    name: shared 
#    external: true
